// AUTO-GENERATED by scripts/translate assembler. 26 restaurants translations (zh).
import type { RestaurantTranslation } from "@/lib/types";

export const restaurants: Record<string, RestaurantTranslation> = {
  "pho-thin-lo-duc": {
    "name": "Thìn炉杜牛肉粉（13号）",
    "address": "炉杜街13号，二征夫人郡",
    "reasons": [
      "猛火爆炒的tái lăn牛肉粉 — 别处找不到的招牌味",
      "河内人从1979年起就在这里吃",
      "总是很热闹但上菜非常快"
    ]
  },
  "pho-bat-dan": {
    "name": "钵担牛肉粉",
    "address": "钵担街49号，还剑郡",
    "reasons": [
      "老城区著名的『先付款排队』牛肉粉",
      "汤清味正，地道老河内风味",
      "排队文化本身就是值得一试的体验"
    ]
  },
  "bun-cha-huong-lien": {
    "name": "香莲烤肉米线",
    "address": "黎文休街24号，二征夫人郡",
    "reasons": [
      "『奥巴马烤肉米线』— 总统用过的餐桌原样保留",
      "奥巴马套餐：烤肉米线＋海鲜春卷＋河内啤酒",
      "空间宽敞，适合多人聚会"
    ]
  },
  "bun-cha-dac-kim": {
    "name": "德金烤肉米线",
    "address": "行绵街1号，还剑郡",
    "reasons": [
      "1966年起就以分量十足闻名",
      "店门口现场炭火烤肉",
      "位于老城区中心，散步时顺路即到"
    ]
  },
  "cha-ca-la-vong": {
    "name": "罗望鱼饼（Chả Cá Lã Vọng）",
    "address": "鱼饼街14号，还剑郡",
    "reasons": [
      "创造了这道菜的百年老店",
      "餐桌上现煎滋滋作响的鱼",
      "只有一道菜 — 无需菜单"
    ]
  },
  "cafe-giang": {
    "name": "Giảng咖啡",
    "address": "阮友珣街39号，还剑郡",
    "reasons": [
      "1946年鸡蛋咖啡的诞生地",
      "阮文Giảng老先生的祖传配方",
      "藏在幽深小巷里 — 地道河内风情"
    ]
  },
  "cafe-dinh": {
    "name": "Đinh咖啡",
    "address": "丁先皇街13号，二楼",
    "reasons": [
      "阳台正对还剑湖",
      "与创办Giảng咖啡的是同一家族",
      "原汁原味保留的老阁楼空间"
    ]
  },
  "bun-bo-ba-tuyet": {
    "name": "Tuyết婆牛肉米线",
    "address": "阮公著街47号，顺化市",
    "reasons": [
      "虾酱香茅汤底，地道顺化老奶奶风味",
      "当地人每天来吃早餐",
      "中午前售罄 — 要早起才赶得上"
    ]
  },
  "bun-bo-dong-ba": {
    "name": "东巴市场牛肉米线",
    "address": "东巴市场，顺化市",
    "reasons": [
      "在百年市场里用餐 — 完整的体验",
      "价格实惠，分量十足",
      "可结合逛市场选购顺化特产"
    ]
  },
  "quan-hanh-nem-lui": {
    "name": "幸餐馆 (Quán Hạnh)",
    "address": "顺化市福德正街11号",
    "reasons": [
      "囊括各种口味的顺化套餐，适合初次尝试者",
      "花生蘸酱备受称赞、远近闻名",
      "服务员会耐心教你如何卷菜"
    ]
  },
  "cao-lau-ba-be": {
    "name": "婆贝高楼面 (Cao lầu Bà Bé)",
    "address": "会安市场，陈富街19号",
    "reasons": [
      "市场内的小摊——最正宗的高楼面口味",
      "面条每天清晨取自祖传作坊窑炉",
      "真正的本地价格"
    ]
  },
  "cao-lau-thanh": {
    "name": "清高楼面 (Cao lầu Thanh)",
    "address": "会安太贤街26号",
    "reasons": [
      "每天现炸的酥脆猪油渣",
      "旅行团少，无需久等",
      "靠近古城，观光后顺路方便"
    ]
  },
  "mi-quang-ba-mua": {
    "name": "梅广面·巴梅 (Mì Quảng Bà Mua)",
    "address": "岘港陈平重街19-21号",
    "reasons": [
      "岘港历史悠久的广面品牌",
      "种类齐全：虾肉、鸡肉、田鸡、黑鱼",
      "空间宽敞，适合家庭聚餐"
    ]
  },
  "mi-quang-1a": {
    "name": "梅广面1A (Mì Quảng 1A)",
    "address": "岘港海防街1A号",
    "reasons": [
      "岘港上班族的心头好",
      "汤汁浓郁醇厚，正宗广南风味",
      "上菜快，适合行程紧凑的游客"
    ]
  },
  "banh-mi-phuong": {
    "name": "凤越式面包 (Bánh mì Phượng)",
    "address": "会安潘周桢街2B号",
    "reasons": [
      "被安东尼·波登称为'全世界最好吃的越式面包'",
      "20多种馅料和自制肉酱",
      "排队比看上去快得多"
    ]
  },
  "banh-mi-huynh-hoa": {
    "name": "琼花越式面包 (Bánh mì Huỳnh Hoa)",
    "address": "第一郡黎氏娟街26号",
    "reasons": [
      "西贡最有名的'全料'越式面包",
      "浓郁的自制肉酱和黄油",
      "营业到深夜——随时能救急充饥"
    ]
  },
  "com-tam-ba-ghien": {
    "name": "巴宪碎米饭 (Cơm tấm Ba Ghiền)",
    "address": "富润郡邓文语街84号",
    "reasons": [
      "'巨型'猪排荣获米其林必比登推介",
      "炭火不间断烧烤——始终热腾腾",
      "从鱼露到葱油都是正宗西贡碎米饭"
    ]
  },
  "com-tam-phuc-loc-tho": {
    "name": "福禄寿碎米饭 (Cơm tấm Phúc Lộc Thọ)",
    "address": "第一郡阮廌街235号",
    "reasons": [
      "干净稳定的连锁店——适合带小孩的家庭",
      "除排骨、猪皮丝、蛋肉饼外菜单丰富多样",
      "分店众多，靠近各旅游景点"
    ]
  },
  "banh-xeo-46a": {
    "name": "煎饼 46A（Bánh xèo）",
    "address": "第一郡丁公壮街46A号",
    "reasons": [
      "深受外国游客喜爱的「巨型煎盘」越式煎饼",
      "外皮酥脆，虾肉与猪肉馅料丰盛",
      "满桌新鲜生菜香草"
    ]
  },
  "banh-xeo-7-toi": {
    "name": "煎饼 7 Tới",
    "address": "芹苴市黄国越街45号",
    "reasons": [
      "地道的湄公河三角洲式煎饼，加椰浆煎得又大又金黄",
      "馅料选用当地特产椰子嫩芯",
      "田园般亲民的价格"
    ]
  },
  "hu-tieu-hong-phat": {
    "name": "粿条 洪发（Hồng Phát）",
    "address": "第三郡武文陈街389号",
    "reasons": [
      "拌酱油的干捞粿条，深受美食行家喜爱",
      "面条弹牙，每天清晨备好新鲜虾肉与猪肉",
      "卖完即歇业——请在上午11点前前往"
    ]
  },
  "hu-tieu-my-tho-tuyet": {
    "name": "美湫粿条 雪姨（Cô Tuyết）",
    "address": "美湫市邑北街",
    "reasons": [
      "在粿条的故乡品尝地道美味",
      "锅葛（Gò Cát）米粉特有的弹韧与透亮",
      "游览湄公河三角洲途中方便顺道品尝"
    ]
  },
  "banh-can-le": {
    "name": "小米饼 丽（Lệ）",
    "address": "大叻市耶尔森街27/44号",
    "reasons": [
      "在微凉的大叻围坐在温暖的炭炉旁",
      "浇上鱼露的烧卖肉丸是点睛之笔",
      "藏在小巷里的小店，满满地道本地味"
    ]
  },
  "banh-can-51": {
    "name": "小米饼 51 苏宪诚（Tô Hiến Thành）",
    "address": "芽庄市苏宪诚街51号",
    "reasons": [
      "芽庄海滨风味的鲜鱿小米饼",
      "现点现做，一炉一炉热腾腾又酥脆",
      "靠近海边，下午顺道品尝很方便"
    ]
  },
  "cheo-leo-cafe": {
    "name": "Cheo Leo 咖啡馆",
    "address": "第三郡阮善述街109/36号",
    "reasons": [
      "西贡最古老的布袋滤泡咖啡馆（1938年）",
      "沿用80年前的方式，在炭炉上用陶壶冲煮",
      "一家三代人至今仍守着这家店"
    ]
  },
  "bun-quay-kien-xay": {
    "name": "搅拌米粉 建赛（Kiến Xây）",
    "address": "富国岛阳东镇白藤街28号",
    "reasons": [
      "富国岛「搅拌米粉」风潮的发源地",
      "通宵营业——钓鱿归来的深夜救星",
      "按你自己的「配方」亲手调蘸料"
    ]
  }
};
