// AUTO-GENERATED by scripts/translate assembler. 26 restaurants translations (en).
import type { RestaurantTranslation } from "@/lib/types";

export const restaurants: Record<string, RestaurantTranslation> = {
  "pho-thin-lo-duc": {
    "name": "Pho Thin 13 Lo Duc",
    "address": "13 Lo Duc, Hai Ba Trung",
    "reasons": [
      "Pho tai lan stir-fried over high heat — a signature you won't find anywhere else",
      "Hanoians have been eating here since 1979",
      "Always crowded but service is very fast"
    ]
  },
  "pho-bat-dan": {
    "name": "Pho Bat Dan",
    "address": "49 Bat Dan, Hoan Kiem",
    "reasons": [
      "The famous 'pay-and-queue' pho of the Old Quarter",
      "Clear broth, true old Hanoi flavor",
      "The queuing culture is an experience worth trying"
    ]
  },
  "bun-cha-huong-lien": {
    "name": "Bun Cha Huong Lien",
    "address": "24 Le Van Huu, Hai Ba Trung",
    "reasons": [
      "'Obama Bun Cha' — the President's table is kept just as it was",
      "The Obama combo: bun cha + seafood spring rolls + Hanoi beer",
      "Spacious, great for large groups"
    ]
  },
  "bun-cha-dac-kim": {
    "name": "Bun Cha Dac Kim",
    "address": "1 Hang Manh, Hoan Kiem",
    "reasons": [
      "Generous portions famous since 1966",
      "Grilled pork over charcoal right at the entrance",
      "In the heart of the Old Quarter, easy to stop by on a stroll"
    ]
  },
  "cha-ca-la-vong": {
    "name": "Cha Ca La Vong",
    "address": "14 Cha Ca, Hoan Kiem",
    "reasons": [
      "A 100-year-old restaurant that created the dish",
      "Sizzling pans of grilled fish right at your table",
      "Just one dish — no menu needed"
    ]
  },
  "cafe-giang": {
    "name": "Cafe Giang",
    "address": "39 Nguyen Huu Huan, Hoan Kiem",
    "reasons": [
      "Birthplace of egg coffee since 1946",
      "The secret family recipe of Mr. Nguyen Van Giang",
      "Down a deep narrow alley — quintessentially Hanoi"
    ]
  },
  "cafe-dinh": {
    "name": "Cafe Dinh",
    "address": "13 Dinh Tien Hoang, 2nd floor",
    "reasons": [
      "A balcony looking straight out over Hoan Kiem Lake",
      "From the same family that founded Cafe Giang",
      "An original, well-preserved old attic space"
    ]
  },
  "bun-bo-ba-tuyet": {
    "name": "Bun Bo Ba Tuyet",
    "address": "47 Nguyen Cong Tru, Hue City",
    "reasons": [
      "Broth with shrimp paste and lemongrass, true to Hue grandma's style",
      "Locals eat here for breakfast every day",
      "Sells out before noon — come early to catch it"
    ]
  },
  "bun-bo-dong-ba": {
    "name": "Bun Bo Dong Ba Market",
    "address": "Dong Ba Market, Hue City",
    "reasons": [
      "Eating inside a century-old market — a complete experience",
      "Affordable prices, generous bowls",
      "Combine it with browsing the market for Hue specialties"
    ]
  },
  "quan-hanh-nem-lui": {
    "name": "Quán Hạnh",
    "address": "11 Pho Duc Chinh, Hue City",
    "reasons": [
      "A Hue-style set meal covering all the flavors, perfect for first-timers",
      "The peanut dipping sauce is famously praised",
      "Staff patiently show you how to roll the wraps"
    ]
  },
  "cao-lau-ba-be": {
    "name": "Cao Lau Ba Be",
    "address": "Hoi An Market, 19 Tran Phu",
    "reasons": [
      "A small stall inside the market — the original cao lau flavor",
      "Noodles from a traditional family kiln every morning",
      "Genuine local prices"
    ]
  },
  "cao-lau-thanh": {
    "name": "Cao Lau Thanh",
    "address": "26 Thai Phien, Hoi An",
    "reasons": [
      "Crispy pork cracklings rendered fresh daily",
      "Few tour groups, so no long waits",
      "Near the old town, convenient after sightseeing"
    ]
  },
  "mi-quang-ba-mua": {
    "name": "Mi Quang Ba Mua",
    "address": "19-21 Tran Binh Trong, Da Nang",
    "reasons": [
      "A long-established Mi Quang brand in Da Nang",
      "Every variation: shrimp-and-pork, chicken, frog, snakehead fish",
      "Spacious setting for families"
    ]
  },
  "mi-quang-1a": {
    "name": "Mi Quang 1A",
    "address": "1A Hai Phong, Da Nang",
    "reasons": [
      "A favorite haunt of Da Nang's office workers",
      "Rich, concentrated broth in true Quang Nam style",
      "Quick service, ideal for a packed itinerary"
    ]
  },
  "banh-mi-phuong": {
    "name": "Banh Mi Phuong",
    "address": "2B Phan Chau Trinh, Hoi An",
    "reasons": [
      "Called 'the best banh mi in the world' by Anthony Bourdain",
      "Over 20 fillings and homemade pâté",
      "The line moves faster than it looks"
    ]
  },
  "banh-mi-huynh-hoa": {
    "name": "Banh Mi Huynh Hoa",
    "address": "26 Le Thi Rieng, District 1",
    "reasons": [
      "Saigon's most famous 'fully loaded' banh mi",
      "Rich homemade pâté and butter",
      "Open late — a lifesaver at any hour"
    ]
  },
  "com-tam-ba-ghien": {
    "name": "Com Tam Ba Ghien",
    "address": "84 Dang Van Ngu, Phu Nhuan",
    "reasons": [
      "The 'giant' pork chop earned a Michelin Bib Gourmand",
      "Grilled over charcoal nonstop — always hot",
      "Authentic Saigon com tam, from the fish sauce to the scallion oil"
    ]
  },
  "com-tam-phuc-loc-tho": {
    "name": "Com Tam Phuc Loc Tho",
    "address": "235 Nguyen Trai, District 1",
    "reasons": [
      "A clean, consistent chain — great for families with young kids",
      "A varied menu beyond ribs, shredded pork skin, and egg meatloaf",
      "Multiple branches, close to tourist spots"
    ]
  },
  "banh-xeo-46a": {
    "name": "Banh Xeo 46A",
    "address": "46A Dinh Cong Trang, District 1",
    "reasons": [
      "'Giant-skillet' banh xeo famous among international travelers",
      "Crispy shell with a generous shrimp and pork filling",
      "A tableful of fresh herbs and greens"
    ]
  },
  "banh-xeo-7-toi": {
    "name": "Banh Xeo 7 Toi",
    "address": "45 Hoang Quoc Viet, Can Tho",
    "reasons": [
      "Authentic Mekong Delta banh xeo, large and golden with coconut milk",
      "Filled with the local specialty of coconut palm heart",
      "Easygoing garden-country prices"
    ]
  },
  "hu-tieu-hong-phat": {
    "name": "Hu Tieu Hong Phat",
    "address": "389 Vo Van Tan, District 3",
    "reasons": [
      "Dry hu tieu tossed in soy sauce, beloved by food connoisseurs",
      "Perfectly chewy noodles with fresh shrimp and pork every morning",
      "Closes when sold out — come before 11am"
    ]
  },
  "hu-tieu-my-tho-tuyet": {
    "name": "Hu Tieu My Tho Co Tuyet",
    "address": "Ap Bac Street, My Tho City",
    "reasons": [
      "Enjoy hu tieu right in its hometown",
      "Distinctive chewy, translucent Go Cat rice noodles",
      "A convenient stop along a Mekong Delta tour"
    ]
  },
  "banh-can-le": {
    "name": "Banh Can Le",
    "address": "27/44 Yersin, Da Lat",
    "reasons": [
      "Sit around a warm charcoal stove in chilly Da Lat",
      "The fish-sauce-soaked pork meatballs are the highlight",
      "A tiny alley eatery, truly local in feel"
    ]
  },
  "banh-can-51": {
    "name": "Banh Can 51 To Hien Thanh",
    "address": "51 To Hien Thanh, Nha Trang",
    "reasons": [
      "Fresh-squid banh can in Nha Trang seaside style",
      "Made to order, hot and crisp batch by batch",
      "Near the beach, an easy afternoon stop"
    ]
  },
  "cheo-leo-cafe": {
    "name": "Cheo Leo Cafe",
    "address": "109/36 Nguyen Thien Thuat, District 3",
    "reasons": [
      "The oldest sock-filter coffee house in Saigon (1938)",
      "Brewed in clay pots over a charcoal stove, just as it was 80 years ago",
      "Three generations of the family still run the shop"
    ]
  },
  "bun-quay-kien-xay": {
    "name": "Bun Quay Kien Xay",
    "address": "28 Bach Dang, Duong Dong, Phu Quoc",
    "reasons": [
      "The birthplace of the Phu Quoc bun quay trend",
      "Open all night — a lifesaver after a squid-fishing trip",
      "Mix your own dipping sauce to your personal 'recipe'"
    ]
  }
};
