// Destination ID → Open-Meteo city key (see weather.ts CITY_COORDS)
export const DESTINATION_CITY_MAP: Record<string, string> = {
  "hoan-kiem-lake":           "ha-noi",
  "old-quarter-hanoi":        "ha-noi",
  "hue-imperial-city":        "hue",
  "golden-bridge":            "da-nang",
  "hoi-an-ancient-town":      "hoi-an",
  "da-lat-city":              "da-lat",
  "ben-thanh-market":         "ho-chi-minh",
  "nha-trang-beach":          "nha-trang",
  "hon-mun-island":           "nha-trang",
  "phu-quoc-island":          "phu-quoc",
  "bai-sao-beach":            "phu-quoc",
  "ha-long-bay":              "ha-long",
  "sa-pa-town":               "sa-pa",
  "moc-chau-plateau":         "sa-pa",
  "lung-cu-flag-tower":       "ha-giang",
  "ma-pi-leng-pass":          "ha-giang",
  "dong-van-old-town":        "ha-giang",
  "trang-an":                 "ninh-binh",
  "phong-nha-cave":           "phong-nha",
  "son-doong-cave":           "phong-nha",
  "mui-ne-sand-dunes":        "mui-ne",
  "cai-rang-floating-market": "can-tho",
  "tra-su-forest":            "can-tho",
  "mieu-ba-chua-xu":          "can-tho",
  "buon-don":                 "da-lat",
  "dray-nur-waterfall":       "da-lat",
  "dien-bien-phu-battlefield":"sa-pa",
};
