// Generate D1 seed SQL from the authoring seeds (Bible 013 — D1 is the source of truth,
// authored as TS for easy review/versioning). Run: npm run db:seed:build
// Then load it:  wrangler d1 execute atlas_db --local --file=db/seed.sql
//
// Every content row carries a `country` column (migration 0006). Slugs and ids only need to
// be unique WITHIN a country, but the tables still key on them alone, so this script fails
// loudly if two atlases ever collide.

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { destinations } from "../src/data/destinations.ts";
import { provinceContent } from "../src/data/provinceContent.ts";
import { destinationI18n, provinceI18n } from "../src/data/i18n/index.ts";
import { dishI18n, restaurantI18n } from "../src/data/i18n/food/index.ts";
import { dishes, restaurants } from "../src/data/food.ts";
import { destinationsKr, provinceContentKr, dishesKr, restaurantsKr } from "../src/data/kr/index.ts";
import { destinationI18nKr, provinceI18nKr, dishI18nKr, restaurantI18nKr } from "../src/data/kr/i18n/index.ts";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, "..");
const r = (p) => resolve(root, p);

const geoMeta = (cc) => JSON.parse(readFileSync(r(`src/data/generated/geo-meta.${cc}.json`), "utf8"));

/** One entry per atlas. */
const ATLASES = [
  {
    cc: "vn",
    geo: geoMeta("vn"),
    provinceContent,
    destinations,
    dishes,
    restaurants,
    destinationI18n,
    provinceI18n,
    dishI18n,
    restaurantI18n,
  },
  {
    cc: "kr",
    geo: geoMeta("kr"),
    provinceContent: provinceContentKr,
    destinations: destinationsKr,
    dishes: dishesKr,
    restaurants: restaurantsKr,
    destinationI18n: destinationI18nKr,
    provinceI18n: provinceI18nKr,
    dishI18n: dishI18nKr,
    restaurantI18n: restaurantI18nKr,
  },
];

const q = (v) => (v === null || v === undefined ? "NULL" : `'${String(v).replace(/'/g, "''")}'`);
const j = (v) => q(JSON.stringify(v ?? []));
const num = (v) => (Number.isFinite(v) ? String(v) : "0");
// i18n overlay column: JSON object of translations, or NULL when none exist.
const i18nCol = (obj) => (obj && Object.keys(obj).length ? q(JSON.stringify(obj)) : "NULL");

// ── Cross-atlas uniqueness guard ──────────────────────────────
const seen = { province: new Map(), destination: new Map(), dish: new Map(), region: new Map() };
const claim = (kind, key, cc) => {
  const owner = seen[kind].get(key);
  if (owner && owner !== cc) {
    throw new Error(
      `[build-d1-seed] ${kind} key "${key}" is used by both "${owner}" and "${cc}". ` +
        `Ids/slugs must be unique across atlases — rename one of them.`,
    );
  }
  seen[kind].set(key, cc);
};

const lines = [];
lines.push("-- Auto-generated by scripts/build-d1-seed.mjs. Do not edit by hand.");
lines.push("PRAGMA foreign_keys = OFF;");
lines.push("DELETE FROM destinations;");
lines.push("DELETE FROM provinces;");
lines.push("DELETE FROM regions;");
lines.push("DELETE FROM restaurants;");
lines.push("DELETE FROM dishes;");

const totals = [];

for (const atlas of ATLASES) {
  const { cc, geo } = atlas;

  geo.regions.forEach((rg, i) => {
    claim("region", rg.id, cc);
    lines.push(
      `INSERT OR REPLACE INTO regions (id, slug, name, name_en, color, display_order, country) VALUES (${q(rg.id)}, ${q(rg.id)}, ${q(rg.name)}, ${q(rg.nameEn)}, ${q(rg.color)}, ${i}, ${q(cc)});`,
    );
  });

  for (const p of geo.provinces) {
    claim("province", p.slug, cc);
    const c = atlas.provinceContent[p.slug];
    lines.push(
      `INSERT OR REPLACE INTO provinces (slug, region_id, name, name_en, region_name, color, center_lng, center_lat, summary, story, best_time, specialties, i18n, country) VALUES (` +
        `${q(p.slug)}, ${q(p.regionId)}, ${q(p.name)}, ${q(p.nameEn)}, ${q(p.regionName)}, ${q(p.color)}, ${num(p.centroid[0])}, ${num(p.centroid[1])}, ` +
        `${q(c?.summary ?? null)}, ${q(c?.story ?? null)}, ${q(c?.bestTime ?? null)}, ${c ? j(c.specialties) : "NULL"}, ${i18nCol(atlas.provinceI18n[p.slug])}, ${q(cc)});`,
    );
  }

  for (const d of atlas.destinations) {
    claim("destination", d.id, cc);
    lines.push(
      `INSERT OR REPLACE INTO destinations (id, slug, province_slug, name, name_en, type, lng, lat, summary, story, facts, travel_tips, best_time, visit_duration, ticket, opening_hours, badges, tags, gallery, nearby, featured, source_url, verified_at, i18n, country) VALUES (` +
        `${q(d.id)}, ${q(d.slug)}, ${q(d.provinceSlug)}, ${q(d.name)}, ${q(d.nameEn)}, ${q(d.type)}, ${num(d.lng)}, ${num(d.lat)}, ` +
        `${q(d.summary)}, ${q(d.story)}, ${j(d.facts)}, ${j(d.travelTips)}, ${q(d.bestTime)}, ${q(d.visitDuration)}, ${q(d.ticket)}, ${q(d.openingHours)}, ` +
        // `gallery` là cột NOT NULL của schema 0001 mà không còn ai đọc: worker thôi SELECT nó,
        // client hỏi manifest. Ghi mảng rỗng cho tới khi có migration bỏ hẳn cột — bỏ cột trước
        // khi worker mới lên sóng thì bản worker cũ sẽ SELECT một cột không còn tồn tại.
        `${j(d.badges)}, ${j(d.tags)}, '[]', ${j(d.nearby)}, ${d.featured ? 1 : 0}, ` +
        `${q(d.sourceUrl ?? null)}, ${q(d.verifiedAt ?? null)}, ${i18nCol(atlas.destinationI18n[d.id])}, ${q(cc)});`,
    );
  }

  // Food Explorer (026)
  for (const d of atlas.dishes) {
    claim("dish", d.id, cc);
    lines.push(
      `INSERT OR REPLACE INTO dishes (id, slug, name, name_en, emoji, summary, story, origin_province, province_slugs, ingredients, flavor, best_time, tags, featured, i18n, country) VALUES (` +
        `${q(d.id)}, ${q(d.id)}, ${q(d.name)}, ${q(d.nameEn)}, ${q(d.emoji)}, ${q(d.summary)}, ${q(d.story)}, ${q(d.originProvince)}, ` +
        `${j(d.provinceSlugs)}, ${j(d.ingredients)}, ${q(d.flavor)}, ${q(d.bestTime)}, ${j(d.tags)}, ${d.featured ? 1 : 0}, ${i18nCol(atlas.dishI18n[d.id])}, ${q(cc)});`,
    );
  }
  for (const rst of atlas.restaurants) {
    lines.push(
      `INSERT OR REPLACE INTO restaurants (id, dish_id, name, province_slug, address, lng, lat, price_range, open_hours, labels, atlas_score, reasons, i18n, country) VALUES (` +
        `${q(rst.id)}, ${q(rst.dishId)}, ${q(rst.name)}, ${q(rst.provinceSlug)}, ${q(rst.address)}, ${num(rst.lng)}, ${num(rst.lat)}, ` +
        `${q(rst.priceRange)}, ${q(rst.openHours)}, ${j(rst.labels)}, ${num(rst.atlasScore)}, ${j(rst.reasons)}, ${i18nCol(atlas.restaurantI18n[rst.id])}, ${q(cc)});`,
    );
  }

  // Provinces with no editorial yet still render on the map — flag them so the gap is visible.
  const missing = geo.provinces.filter((p) => !atlas.provinceContent[p.slug]).map((p) => p.slug);
  totals.push(
    `${cc}: ${geo.regions.length} regions, ${geo.provinces.length} provinces (${missing.length} without editorial), ` +
      `${atlas.destinations.length} destinations, ${atlas.dishes.length} dishes, ${atlas.restaurants.length} restaurants`,
  );
  if (missing.length) console.warn(`[build-d1-seed] ${cc}: no editorial yet for ${missing.join(", ")}`);
}

lines.push("PRAGMA foreign_keys = ON;");

mkdirSync(r("db"), { recursive: true });
writeFileSync(r("db/seed.sql"), lines.join("\n") + "\n");
for (const t of totals) console.log(`[build-d1-seed] ${t}`);
console.log("[build-d1-seed] -> db/seed.sql");
