// Generate D1 seed SQL from the authoring seed (Bible 013 — D1 is the source of truth,
// authored as TS for easy review/versioning). Run: npm run db:seed:build
// Then load it:  wrangler d1 execute atlas_db --local --file=db/seed.sql

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { destinations } from "../src/data/destinations.ts";
import { provinceContent } from "../src/data/provinceContent.ts";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, "..");
const r = (p) => resolve(root, p);

const geo = JSON.parse(readFileSync(r("src/data/generated/geo-meta.json"), "utf8"));

const q = (v) => (v === null || v === undefined ? "NULL" : `'${String(v).replace(/'/g, "''")}'`);
const j = (v) => q(JSON.stringify(v ?? []));
const num = (v) => (Number.isFinite(v) ? String(v) : "0");

const lines = [];
lines.push("-- Auto-generated by scripts/build-d1-seed.mjs. Do not edit by hand.");
lines.push("PRAGMA foreign_keys = OFF;");
lines.push("DELETE FROM destinations;");
lines.push("DELETE FROM provinces;");
lines.push("DELETE FROM regions;");

geo.regions.forEach((rg, i) => {
  lines.push(
    `INSERT OR REPLACE INTO regions (id, slug, name, name_en, color, display_order) VALUES (${q(rg.id)}, ${q(rg.id)}, ${q(rg.name)}, ${q(rg.nameEn)}, ${q(rg.color)}, ${i});`,
  );
});

for (const p of geo.provinces) {
  const c = provinceContent[p.slug];
  lines.push(
    `INSERT OR REPLACE INTO provinces (slug, region_id, name, name_en, region_name, color, center_lng, center_lat, summary, story, best_time, specialties) VALUES (` +
      `${q(p.slug)}, ${q(p.regionId)}, ${q(p.name)}, ${q(p.nameEn)}, ${q(p.regionName)}, ${q(p.color)}, ${num(p.centroid[0])}, ${num(p.centroid[1])}, ` +
      `${q(c?.summary ?? null)}, ${q(c?.story ?? null)}, ${q(c?.bestTime ?? null)}, ${c ? j(c.specialties) : "NULL"});`,
  );
}

for (const d of destinations) {
  lines.push(
    `INSERT OR REPLACE INTO destinations (id, slug, province_slug, name, name_en, type, lng, lat, summary, story, facts, travel_tips, best_time, visit_duration, ticket, opening_hours, badges, tags, gallery, nearby, featured) VALUES (` +
      `${q(d.id)}, ${q(d.slug)}, ${q(d.provinceSlug)}, ${q(d.name)}, ${q(d.nameEn)}, ${q(d.type)}, ${num(d.lng)}, ${num(d.lat)}, ` +
      `${q(d.summary)}, ${q(d.story)}, ${j(d.facts)}, ${j(d.travelTips)}, ${q(d.bestTime)}, ${q(d.visitDuration)}, ${q(d.ticket)}, ${q(d.openingHours)}, ` +
      `${j(d.badges)}, ${j(d.tags)}, ${j(d.gallery)}, ${j(d.nearby)}, ${d.featured ? 1 : 0});`,
  );
}

lines.push("PRAGMA foreign_keys = ON;");

mkdirSync(r("db"), { recursive: true });
writeFileSync(r("db/seed.sql"), lines.join("\n") + "\n");
console.log(
  `[build-d1-seed] ${geo.regions.length} regions, ${geo.provinces.length} provinces, ${destinations.length} destinations -> db/seed.sql`,
);
